Gemfile.lock
README.md
lib/checkout_sdk/api_resource.rb
lib/checkout_sdk/version.rb
spec/checkout_sdk/api_resource_spec.rb

* Fix payment request endpoint to request_payment
* Update readme

Fix payment request endpoint to request_payment

---

.rubocop.yml
lib/checkout_sdk/api_client.rb
lib/checkout_sdk/checkout_utils.rb
lib/checkout_sdk/tokens/wallet_token_request.rb
spec/checkout_sdk/customers/customers_integration_spec.rb
spec/checkout_sdk/customers/previous/customers_integration_spec.rb
spec/checkout_sdk/disputes/disputes_integration_spec.rb
spec/checkout_sdk/disputes/previous/disputes_integration_spec.rb
spec/checkout_sdk/instruments/instruments_integration_spec.rb
spec/checkout_sdk/instruments/instruments_previous_integration_spec.rb
spec/checkout_sdk/payments/payment_actions_integration_spec.rb
spec/checkout_sdk/payments/previous/payment_actions_integration_spec.rb

Added Support for Http Metadata on Responses
Added Items Wrapper to Array Responses

Added Support for Http Metadata and Items wrapper

---

lib/checkout_sdk/version.rb

* Removes Klarna/Sepa modules
* Added support for Customers (previous)
* Added Support for ALMA source (default)
* Added Support for One Klarna source (default)
* Added Support for Fawry source (default)
* Added missing fields for PayPal source (default)
* Added Support for Payments (previous)
* Added support for Instruments (previous)
* Added support for Disputes (previous)
* Added support for Sources (previous)
* Added Support for Http Metadata on Responses
* Added Items Wrapper to Array Responses
* Added support for APM Sources (previous)

Release 1.0.0.beta.1

---

lib/checkout_sdk/version.rb

* Added `upgrade_reason` to 3DS request and response.
* Removed payment_type: `unscheduled`
* Added support for Customer Source.
* Added support for `hosted payments` and `payment links` (CS1/CS2)
* Added support for Payments Query (CS2)
* Added support for Reports (CS2)
* Added support for Accounts (CS2)
* Added support for Workflows (CS2)
* Added support for custom `http client`

Release 1.0.0.beta.2

---

lib/checkout_sdk/version.rb

* Added support for Risk (CS2)
* Added support for Transfers & Balances (CS2)
* Added support for Logging and Custom logger
* Added support for Reconciliation (CS1)
* Added support for redirect responses for `http client`
* Added support for Webhooks and Events (CS1)

Release 1.0.0.beta.3

---

lib/checkout_sdk/accounts/accounts_client.rb
lib/checkout_sdk/payments/payment_recipient.rb
lib/checkout_sdk/payments/previous/source/id_source.rb
lib/checkout_sdk/payments/previous/source/token_source.rb
lib/checkout_sdk/payments/source/id_source.rb
lib/checkout_sdk/payments/source/token_source.rb
lib/checkout_sdk/risk/risk_client.rb
lib/checkout_sdk/transfers/transfers_client.rb
spec/checkout_sdk/payments/hosted/hosted_payments_integration_spec.rb
spec/checkout_sdk/payments/hosted/previous/hosted_payments_integration_spec.rb
spec/checkout_sdk/payments/links/payment_links_integration_spec.rb
spec/checkout_sdk/payments/links/previous/payment_links_integrattion_spec.rb
spec/support/data_factory.rb

* Added mandatory fields for MIT/CIT payments sources (CS1/CS2)
* Support Secret Key for Accounts & Transfers (CS2)
* Deprecated Risk client (CS1/CS2)
* Added `first_name` and `country` fields for PaymentRecipient schema

API Updates

---

lib/checkout_sdk/version.rb
spec/checkout_sdk/workflows/workflows_actions_integration_spec.rb
spec/checkout_sdk/workflows/workflows_events_integration_spec.rb
spec/checkout_sdk/workflows/workflows_reflow_integration_spec.rb

* Adds support for Dispute Scheme Files
* Adds support for Card Metadata API (CS2)
* Added mandatory fields for MIT/CIT payments sources (CS1/CS2)
* Support Secret Key for `Accounts` & `Transfers` (CS2)
* Deprecated `Risk` client (CS1/CS2)
* Added `first_name` and `country` fields for PaymentRecipient schema

Release 1.0.1

---

lib/checkout_sdk/version.rb

* Adds Integrated Platform Payments Support
* Renames created workflows in tests to add SDK identifier
* Update Sepa URL for PPro actions
* Downgrades Faraday version to be backward compatible

Release 1.0.2

---

lib/checkout_sdk/version.rb

* Added API key auth to Integrated Platforms Balances (CS2)
* Added patch endpoint for payment instruments (CS2)
* Add missing classes and properties for Accounts (CS2)
* Review payment & payout request schemas (CS1/CS2)
* Replace ‘reporting’ scopes with 'reports' on the Reports API (CS2)
* Add new Illicado APM (CS2)

Release 1.0.3

---

lib/checkout_sdk/common/payment_source_type.rb
lib/checkout_sdk/payments/payments.rb
lib/checkout_sdk/payments/source/apm/sepa_source.rb
spec/checkout_sdk/payments/request_apm_payments_integration_spec.rb

~~Add new properties for payment.processing response~~
~~[Add properties for payment.processing response by yelena-pakumirzakova-cko · Pull Request #820 · checkout/checkout-api-reference](https://github.com/checkout/checkout-api-reference/pull/820)~~
[Add SEPAV4 sources by andre-lopes-cko · Pull Request #829 · checkout/checkout-api-reference](https://github.com/checkout/checkout-api-reference/pull/829)

Add SEPAV4 sources

---

lib/checkout_sdk/version.rb

* Fixes logger builder to return builder instance
* Added SEPAV4 sources
* Adds support for Financial Actions API

Release 1.0.4

---

lib/checkout_sdk/payments/processing_settings.rb
lib/checkout_sdk/payments/refund_request.rb

* Adds ‘amount_allocations‘ field to ‘RefundRequest‘ (CS2)
* Adds ‘line_of_business‘ field to ‘PaymentRequest‘ (CS2)

Api Update

---

lib/checkout_sdk/version.rb

* Fixed metadata object on responses
* Added support for hash requests to avoid objects serialization
* Adds ‘amount_allocations‘ field to ‘RefundRequest‘ (CS2)
* Adds ‘line_of_business‘ field to ‘PaymentRequest‘ (CS2)

Release 1.1.0

---

lib/checkout_sdk/version.rb

* Add javascript_enabled field in ChannelData for request session and update session (browser channel)
* Add reference property to Financial Actions query
* Add support for Forex (FX) rates API
* Remove marketplace from HostedPayments & PaymentLinks

Release 1.1.2

---

lib/checkout_sdk/version.rb

* Adds `card_token` object to `PaymentInstrumentRequest` for Integrated Platforms (CS2)
* Adds `if-match` header to `UpdatePaymentInstrumentRequest` for Integrated Platforms (CS2)
* Fixes typo for `TransactionCurrencyAmount` in Financial Actions (CS2)
#115

Release 1.1.3

---

lib/checkout_sdk/version.rb

* Updates conflict response for onboard sub entity operation to include ID
* Adds `authentication_status_reason` to 3ds object in the GET payment details response.
* Adds support for `Cardholders` operations [Issuing]
* Adds support for `Cards` operations [Issuing]
* Adds support for `Card Controls` operations [Issuing]
* Adds support for `Card Testing` operations [Issuing]
* Adds support for `simulate_increment` for `Card Testing`
* Adds support for `simulate_clearing` for `Card Testing`
* Adds support for `simulate_reversal` for `Card Testing`
#117 
#120 
#121 
#122 
#123 
#124

Release 1.1.4

---

.github/workflows/build-master.yml
.github/workflows/build-pull-request.yml
.github/workflows/build-release.yml
lib/checkout_sdk/api_client.rb
lib/checkout_sdk/checkout_api.rb
lib/checkout_sdk/payments/contexts/payment_contexts_client.rb
lib/checkout_sdk/payments/payments.rb
spec/checkout_sdk/payments/contexts/contexts_helper.rb
spec/checkout_sdk/payments/contexts/contexts_integration_spec.rb
spec/checkout_sdk/payments/request_apm_payments_integration_spec.rb
spec/checkout_sdk/sessions/sessions_integration_spec.rb
spec/spec_helper.rb
spec/support/data_factory.rb

- Adds request and get `payment contexts` endpoints

Payment Contexts Support (CS2)

---

lib/checkout_sdk/version.rb

- Adds request and get `payment contexts` endpoints

Release 1.1.5

---

lib/checkout_sdk/version.rb

- Adds `payment sessions` support
- Update `payment request` for `payment contexts`
- Update `giropay` source
- Update properties and tests

Release 1.1.6

---

lib/checkout_sdk/accounts/company_verification.rb
lib/checkout_sdk/accounts/company_verification_type.rb
lib/checkout_sdk/accounts/entity_financial_details.rb
lib/checkout_sdk/accounts/individual.rb
lib/checkout_sdk/accounts/onboard_entity.rb
lib/checkout_sdk/accounts/onboard_sub_entity_documents.rb
lib/checkout_sdk/accounts/representative.rb
lib/checkout_sdk/accounts/tax_verification.rb
lib/checkout_sdk/accounts/tax_verification_type.rb
lib/checkout_sdk/sessions/completion/non_hosted_completion_info.rb
spec/checkout_sdk/disputes/disputes_integration_spec.rb
spec/checkout_sdk/payments/request_apm_payments_integration_spec.rb
spec/checkout_sdk/payments/sessions/sessions_integration_spec.rb

- Update onboard sub-entity request
- Update non hosted completion properties
- Update financial details
- Fix tests

Update Completion, Onboard and Financial

---

lib/checkout_sdk/version.rb

- Adds compiled submitted evidence endpoint to disputes
- Update onboard sub-entity request
- Update non hosted completion properties
- Update financial details
- Update hosted payment request with disabled payment methods
- Fix tests

Release 1.1.7

---

spec/checkout_sdk/payments/contexts/contexts_helper.rb
spec/checkout_sdk/payments/contexts/contexts_integration_spec.rb

- Adds Klarna Payment Context Support

Klarna Payment Context Support

---

lib/checkout_sdk/common/instrument_type.rb
lib/checkout_sdk/instruments/create/instrument_data.rb
lib/checkout_sdk/instruments/create/instrument_sepa.rb
lib/checkout_sdk/instruments/instruments.rb
lib/checkout_sdk/payments/payment_request.rb
spec/checkout_sdk/instruments/instruments_integration_spec.rb

- Adds SEPA Direct Debit Core Support

SEPA Direct Debit Core Support

---

lib/checkout_sdk/payments/source/apm/ideal_source.rb
lib/checkout_sdk/sessions/authentication_type.rb
spec/checkout_sdk/payments/request_apm_payments_integration_spec.rb

- Ideal Payment Update (CS2)
- Sessions Authentication Type Update

Ideal Payment Update (CS2). Sessions Authentication Type Update

---

lib/checkout_sdk/version.rb

- Adds SEPA Direct Debit Core Support
- Adds Klarna Payment Context Support
- Update profile class with holding currencies
- Update Ideal Payment (CS2)
- Update Sessions Authentication Type

Release 1.1.8

---

lib/checkout_sdk/version.rb

- Updates DNS Merchant regular expression length

Release 1.2.1

---

lib/checkout_sdk/version.rb

- Updates Knet APM payment
- Updates Workflow properties and endpoints

Release 1.2.2

---

lib/checkout_sdk/version.rb

- Adds VISA EMV 3DS rsupport
- Enhances parse_response Method to Improve Error Handling and Logging
- Updates accounts endpoint properties
- Updates account holders object
- Updates Paypal source properties
- Updates payment sources properties
- Updates payment hosted properties
- Updates payment links properties
- Updates payment sessions properties
- Updates tests

Release 1.2.3

---

lib/checkout_sdk/version.rb
spec/checkout_sdk/apm/previous/klarna/klarna_client_integration_spec.rb
spec/checkout_sdk/events/events_integration_spec.rb
spec/checkout_sdk/payments/hosted/previous/hosted_payments_integration_spec.rb
spec/checkout_sdk/payments/links/previous/payment_links_integrattion_spec.rb
spec/checkout_sdk/webhooks/webhooks_integration_spec.rb

- Updates Hosted Payment Page Payment Contexts and Tests
- feat: Adds `store_for_future_use` Property and Update Tests

Release 1.3.0

---

lib/checkout_sdk/version.rb

- feat: adds ForwardClient and integrate with CheckoutApi
- feat: adds currency attribute to TransferSource and update related methods

Release 1.4.0
